[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Need to set gas at 100m
gas_limit = 100000000
gas_reports = ['*']
gas_price = 169_000_000_000
block_base_fee_per_gas = 100_000_000_000



# See more config options https://github.com/foundry-rs/foundry/tree/master/config